# Generated by Django 2.2.6 on 2019-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=150, unique=True, verbose_name='Produto')),
                ('fornecedor', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('contrato', models.CharField(max_length=20, verbose_name='Contrato')),
                ('aquisicoes', models.IntegerField(verbose_name='Aquisições')),
                ('quantidade_disponivel', models.IntegerField(verbose_name='Quantidade Disponível')),
                ('reservadas', models.IntegerField(verbose_name='Reservadas')),
                ('estoque', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Estoque')),
            ],
        ),
    ]
