# Generated by Django 2.2.6 on 2019-10-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='estoque',
            field=models.IntegerField(blank=True, default='total_estoque', editable=False, null=True, verbose_name='Estoque'),
        ),
    ]
